name: http_manager
description: A starting point for Dart libraries or applications.
version: 0.0.6
author: Vince Kieft <vincekieft1997@gmail.com>
homepage: http://vincekieft.nl

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
